### PR TITLE
Add major parts

### PR DESCRIPTION
**Pull request by RDIL**
Adds a lot of the basic stuff.  
@fkorotkov PTAL.  Also - when are GitHub actions triggered at?

### CODE REVIEW

**Comment by fkorotkov** [comment]
I was in the middle of writing this comment when you merged. Sorry, I'm not that fast. 😅 

GitHub actions won't be executed within Cirrus CI context. Instead it will have it's own environment (see the [docs](https://developer.github.com/actions/creating-github-actions/accessing-the-runtime-environment/)).

In this case instead of `CIRRUS_*` environment variables we'd like to get all information from `GITHUB_EVENT_PATH`. In this case we are going to activate the action on [`check_suite` event](https://developer.github.com/v3/activity/events/types/#checksuiteevent) (see an[ example of the payload in email repo](https://developer.github.com/v3/activity/events/types/#checksuiteevent)).

As you can see from the event payload it's very generic:

- `. check_suite.app` gives you the name and avatar of the app.
- `. check_suite.conclusion ` tells you if it fails or not.
- `.check_suite.branch` and `.check_suite.head_commit.message` tells you information about the change.

So the idea will be to use the payload to construct the webhook payload. Let's work on this in a separate PR. 🙌

**Comment by RDIL** [comment]
Haha LOL, I need to slow down then!  Oh, I see.  Makes more sense.  I'm also going to try to implement it so it can read the webhook URL from a `.txt` file.  I'll open another PR in a second.

**Comment by fkorotkov** [comment]
The action should probably read the URL from an environment variable like email action read it from `APP_NAME` variable: https://github.com/cirrus-actions/email/blob/master/README.md

**Comment by RDIL** [comment]
👍

**Pull request merged**
